expected_texts = {
    'Empowering Candidates to Realize their Fullest  Potential':'wpb_wrapper',
    'Orchestrates workflow for  Candidates to connect and engage with Employers, Universities, and Non-Profits in the Peozzle Marketplace. ':'wpb_wrapper',
    'LAUNCH NOW':'wpb_wrapper',
    'Request Demo':'wpb_wrapper',
    'Opportunity Network':'wpb_wrapper',
    'Build and Manage your private Opportunity network connecting employers, non–profits, and universities to collaborate on finding you the next best job, internship, and volunteering opportunities.':'wpb_wrapper',
    'Intelligent Tools':'wpb_wrapper',
    'AI/ML fueled tools empower Talent and employers to identify the best-qualified candidates for the organization and Talent to find their best-fit jobs.':'wpb_wrapper',
    'PeozzleConnect Mobile App':'wpb_wrapper',
    'PeozzleConnect Mobile App allows candidates, Non-Profits, and employers partners to connect, engage and collaborate on hiring, onboarding, and employment workflows.':'wpb_wrapper',
    'Video Resumes':'wpb_wrapper',
    'Patented* Peozzle Multi-Media resume tool, supports reception, storing, screening, and processing of Video Resumes, an emerging trend.':'wpb_wrapper',
    '360 Assessment':'wpb_wrapper',
    'The holistic Assessment view depicts the graphical view of the Candidate profile, skills, experience fit, along with Peozzle Match Score*.':'wpb_wrapper',
    'Time Management':'wpb_wrapper',
    'The Integrated Timesheet tool allows consultants and staffing agency managers to capture, track, and report timesheet workflow.':'wpb_wrapper',
    'A Hiring Marketplace solution':'wpb_wrapper',
    'Candidates and Consultants need a hiring marketplace to connect, engage with their Employees, Staffing Agencies, and Universities.':'wpb_wrapper',
    'The siloed and manual staffing management process, application-driven engagement between employees, and lack of long-term relationships with the potential employers restrict both Candidates/Consultants. They find their next best opportunity and track their employment and project engagements in a single place. The PeozzleConnect provides a unified engagement environment for talent seekers and providers to address these challenges.':'wpb_wrapper',
    'PeozzleConnect enables professionals and consultants to connect and engage with Employers, Staffing Agencies, and Universities. AI-powered workflows, Mobile and  Timesheet tools allow professionals to match jobs, manage/share profiles and manage the workplace time.':'wpb_wrapper',
    'Connection and Relationships are key for Candidates, Recruiters, and Hiring Companies to realize the respective Potential.':'wpb_wrapper',
    'Network Approach':'wpb_wrapper',
    'Enables Employers, Staffing Agencies, Universities to build a purpose-built business network, which accelerates hiring the right talent.':'wpb_wrapper',
    'Mobile Application':'wpb_wrapper',
    'Peozzle Mobile App allows Peozzle stakeholders to connect, engage and collaborate on hiring, onboarding, and employment workflows.':'wpb_wrapper',
    'Empower staffing agencies and job seekers to identify and Hire the best-fit candidates for the Organization.':'wpb_wrapper',
    'Intelligent Automation':'wpb_wrapper',
    'Peozzle Analytics':'wpb_wrapper',
    'Explore PeozzleConnect Solution':'wpb_wrapper',
    'Empower the recruitment teams across employers, Agencies, and universities with real-time performance, sourcing, and market data insights.':'wpb_wrapper',
    'Role-based portals and Context-driven Workflows provide seamless Experience to Candidates, Consultants, and talent-seeking organizations.':'wpb_wrapper',
    'ENROLL':'wpb_wrapper',
    'ENGAGE':'wpb_wrapper',
    'SOURCE':'wpb_wrapper',
    'HIRE':'wpb_wrapper',
    'MANAGE':'wpb_wrapper',
    'Enroll':'wpb_wrapper',
    'Invite/Enlist Candidates/Consultants':'wpb_wrapper',
    'Invite/Enlist Engage Employees':'wpb_wrapper',
    'HOW PEOZZLE CAN HELP YOUR HIRING TRANSFORMATION JOURNEY':'wpb_wrapper',
    'We are bringing a fresh , network based, and data driven Talent acquisition approach to the Hiring Teams and Candidates':'wpb_wrapper',
    'Peozzle Platform':'wpb_wrapper',
    'Uses cloud-native technologies to offer modular, scalable business, hiring, and career services workflow automation.':'wpb_wrapper',
    'Patented Technology':'wpb_wrapper',
    'The approved USPTO patents are powering the Peozzle platform. 1)Resource Distribution system 2)Multimedia Resume distribution system.':'wpb_wrapper',
    'Peozzle Analytics':'wpb_wrapper',
    'Native Cloud Analytics technologies make the reporting & analytics of Agency, Campus, Hire, Connect, and Serve products easier.':'wpb_wrapper',
    'Peozzle AI/ML Mode':'wpb_wrapper',
    'Purpose-driven screening and AI/ML Model provide insights into the data-driven hiring process.':'wpb_wrapper',
    'Why Peozzle Platform?':'wpb_wrapper',
    'We are grounded in People First Approach. Peozzle Platform empowers the hiring team, candidates, students, university placement office, partners, and everybody in between to realize their fullest potential.':'wpb_wrapper',
    '1098+':'wpb_wrapper',
    'GROWING NETWORK':'wpb_wrapper',
    '2300+':'wpb_wrapper',
    'ACTIVE USERS':'wpb_wrapper',
    'Connect with':'wpb_wrapper',
    'Products':'wpb_wrapper',
    'Peozzle Hire':'wpb_wrapper',
    'Peozzle Agency':'wpb_wrapper',
    'Peozzle Campus':'wpb_wrapper',
    'Peozzle Connect':'wpb_wrapper',
    'Peozzle Serve':'wpb_wrapper',
    'Solutions':'wpb_wrapper',
    'Staffing Automation':'wpb_wrapper',
    'Recruitment':'wpb_wrapper',
    'Campus Recruitment':'wpb_wrapper',
    'Volunteer Management':'wpb_wrapper',
    'Alumni Management':'wpb_wrapper',
    'Peozzle Mobile':'wpb_wrapper',
    'Resources':'wpb_wrapper',
    'Datasheet':'wpb_wrapper',
    'Mission':'wpb_wrapper',
    'Contact us':'wpb_wrapper',
    'Copyright © 2024 Peozzle Corporation. Patented.':'wpb_wrapper',
   
}
