
expected_texts = {
    'Networked Approach for Connecting Volunteers, Non-Profits, and Service Organizations':'wpb_wrapper',
    'Harmonizes Non-Profit Administrators, Volunteers, and  organization workflow to streamline Volunteer Management and increase their customer experience.':'wpb_wrapper',
    'LAUNCH NOW':'wpb_wrapper',
    'Request Demo':'wpb_wrapper',
    'Community Network':'wpb_wrapper',
    'Build and Manage your private Community network connecting your volunteers, non–profits, and needy organizations to connect and collaborate on sourcing the exemplary Volunteers.':'wpb_wrapper',
    'Intelligent Tools':'wpb_wrapper',
    "AI/ML fueled tools empower placement officers and employers to identify the best-qualified Volunteers that meet the individual organization's needs.":'wpb_wrapper',
    'Campus Mobile App':'wpb_wrapper',
    'PeozzleServe Mobile App allows Volunteers, Non-Profits Admin and employers partners to connect and realize their individual needs.':'wpb_wrapper',
    'Video Resumes':'wpb_wrapper',
    'Patented* Peozzle Multi-Media resume tool, supports reception, storing, screening, and processing of Video Resumes, an emerging trend.':'wpb_wrapper',
    '360 Assessment':'wpb_wrapper',
    'The holistic Assessment view depicts the graphical view of the Volunteer profile, skills, experience fit, and Peozzle Match Score*.':'wpb_wrapper',
    'Time Management':'wpb_wrapper',
    'Integrated Timesheet tool allows volunteers and nonprofit administrators to capture, track and report timesheet workflow.':'wpb_wrapper',
    'A Digital Solution for Volunteer Management':'wpb_wrapper',
    'Non-Profit Administrators and Volunteer Manager need to adopt a global networked approach to connect, engage with Volunteers, other non-profit entities, and employers.':'wpb_wrapper',
    'The manual Volunteer Management process, project-driven engagement with volunteers,  lack of connection to non-profit entities restrict both Non-Profit Administrators and Volunteer managers. Attracting qualified volunteers to build a healthy pipeline of skilled, service-minded volunteers and ready to serve the needy are the challenges in today’s world.':'wpb_wrapper',
    'Administrators and Volunteer Managers mostly rely upon email lists, social media sites, and siloed engagement tools. Still, they cannot fully realize the outcomes needed to operate the Non-Profit entities effectively. Further, both Non-Profit Teams, Volunteer Manager and Volunteers teams, lack insights on the available opportunities.':'wpb_wrapper',
    'PeozzleServe enables Non-Profits to build a global volunteer network, unifying non-profit Administrators and volunteers’ engagement and Volunteer Management workflows. Role-based portal, Mobile App allows administrators and Volunteers to connect and serve their communities seamlessly.':'wpb_wrapper',
    'Serving the Community is a Team Effort! Synchronized Orchestration is the key to delivering the Outcomes!':'wpb_wrapper',
    'HOW PEOZZLE CAN HELP YOUR HIRING TRANSFORMATION JOURNEY':'wpb_wrapper',
    'We are bringing a fresh , network based, and data driven Talent acquisition approach to the Hiring Teams and Candidates':'wpb_wrapper',
    'Peozzle Platform':'wpb_wrapper',
    'Uses cloud-native technologies to offer modular, scalable business, hiring, and career services workflow automation.':'wpb_wrapper',
    'Patented Technology':'wpb_wrapper',
    'The approved USPTO patents are powering the Peozzle platform. 1)Resource Distribution System 2)Multimedia Resume Distribution System.':'wpb_wrapper',
    'Peozzle Marketplace':'wpb_wrapper',
    'Help to build scalable enterprise solutions to broader the talent management solutions.':'wpb_wrapper',
    'Peozzle Analytics':'wpb_wrapper',
    'Cloud-native analytics technologies make the reporting & analytics of Agency, Campus, Hire, Connect, and Serve products easier.':'wpb_wrapper',
    'Peozzle AI/ML Model':'wpb_wrapper',
    'Purpose-driven screening and AI/ML model provide insights into the data-driven hiring process.':'wpb_wrapper',
    'Why Peozzle Platform?':'wpb_wrapper',
    'We are grounded in People First Approach. Peozzle Platform empowers the hiring team, candidates, students, university placement office, partners, and everybody in between to realize their fullest potential.':'wpb_wrapper',
     '1098+':'wpb_wrapper',
    'GROWING NETWORK':'wpb_wrapper',
    '2300+':'wpb_wrapper',
    'ACTIVE USERS':'wpb_wrapper',
    'Connect with':'wpb_wrapper',
    'Products':'wpb_wrapper',
    'Peozzle Hire':'wpb_wrapper',
    'Peozzle Agency':'wpb_wrapper',
    'Peozzle Campus':'wpb_wrapper',
    'Peozzle Connect':'wpb_wrapper',
    'Peozzle Serve':'wpb_wrapper',
    'Solutions':'wpb_wrapper',
    'Staffing Automation':'wpb_wrapper',
    'Recruitment':'wpb_wrapper',
    'Campus Recruitment':'wpb_wrapper',
    'Volunteer Management':'wpb_wrapper',
    'Alumni Management':'wpb_wrapper',
    'Peozzle Mobile':'wpb_wrapper',
    'Resources':'wpb_wrapper',
    'Datasheet':'wpb_wrapper',
    'Mission':'wpb_wrapper',
    'Contact us':'wpb_wrapper',
    'Copyright © 2024 Peozzle Corporation. Patented.':'wpb_wrapper',
   
}